Vagrant.configure("2") do |config|
    # Ubuntu Focal (20.04) tabanlı bir image kullanıyoruz
    config.vm.box = "ubuntu/focal64"
    #########################################
    # NFS Sunucu Tanımı
    #########################################
    config.vm.define "nfs" do |nfs|
      nfs.vm.hostname = "nfs"
      nfs.vm.network "private_network", ip: "192.168.56.30"
      
      nfs.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus   = 2
      end
  
      # NFS sunucusunun kurulumu ve ayarlarının yapılması
      nfs.vm.provision "shell", inline: <<-SHELL

        sudo apt-get update
        
        sudo apt-get install -y nfs-kernel-server

        sudo mkdir -p /nfsshare
        sudo chmod 777 /nfsshare
        
        if ! grep -q "/nfsshare" /etc/exports; then
          echo "/nfsshare 192.168.56.0/24(rw,sync,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports
        fi
        
        sudo exportfs -rav
        
        sudo systemctl restart nfs-kernel-server
        
        echo "NFS Exports:"
        sudo exportfs -v
      SHELL
    end
  end
  
